language: php
php:
  - 7
sudo: false
branches:
  only:
    - source
cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR
before_script:
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction
script:
  - php scripts/build.php -e=prod
after_success:
  - bash scripts/deploy.sh
